### ISSUE TITLE
will it work in Windows 10?

### ISSUE THREAD

**Issue by Sandy4321** [lukassykora/actionrules#15]
will it work in Windows 10?

**Comment by lukassykora** [comment]
It works in Windows 10. You just need to install a dependency PyFIM in correct way (it can not be installed by pip). Check http://www.borgelt.net/pyfim.html. Basically you just need to copy a file to site-packages folder.

**Comment by Sandy4321** [comment]
I see thanks for soon answer
By the way do you have short description of action rules
Since book is behind pay wall and it is very long as all books are
So short description to understand idea would help

**Comment by lukassykora** [comment]
I recommend to se the notebook about Titanic for better understanding: https://github.com/lukassykora/actionrules/blob/master/notebooks/Titanic%20-%20Action%20Rules.ipynb

**Comment by Sandy4321** [comment]
great material thanks
by the way, what is used to find  rules used for classification
as you wrote
Action rule mining is an extension of the widely used task of learning classification rules
so you first find  classification rules (how? what algorithm used?)
and use these classification rules to calculate action rules
 
as we see
- desired_changes - List of desired changes. For example, [["0", "1"]].
then if there are too many desired changes in  List of desired_changes 
then it will be many ways to get answer
so how you define what is best answer is
what kind of optimization algorithms is used?

thanks

**Comment by lukassykora** [comment]
It uses PyFIM, there is the link in the notebook.
