### ISSUE TITLE
Problem installing package on linux

### ISSUE THREAD

**Issue by kliegr** [lukassykora/actionrules#18]
pip install https://test.pypi.org/simple/ actionrules-lukassykora

Gives errror
    ERROR: Cannot unpack file /tmp/pip-unpack-26bij12f/simple (downloaded from /tmp/pip-req-build-qor_7uw6, content-type: text/html; charset=UTF-8); cannot detect archive format

    pip install -i https://test.pypi.org/simple/ actionrules-lukassykora

Gives errror

Collecting actionrules-lukassykora
  Using cached https://test-files.pythonhosted.org/packages/4a/63/c1bf588c34102d80b0c3244cc571d6a1636618a2db77cef28cfe9ff6fec3/actionrules_lukassykora-1.0.18-py3-none-any.whl
Collecting typing (from actionrules-lukassykora)
  ERROR: Could not find a version that satisfies the requirement typing (from actionrules-lukassykora) (from versions: none)
ERROR: No matching distribution found for typing (from actionrules-lukassykora)

**Comment by lukassykora** [comment]
There could be several reasons:
1) The old version of pip. You need run (https://stackoverflow.com/questions/49748063/pip-install-fails-for-every-package-could-not-find-a-version-that-satisfies):
`curl https://bootstrap.pypa.io/get-pip.py | python`
2) Typing library is a backport of the standard library typing module to Python versions older than 3.5. If you have the latest version the library should not have any effect. But it should be possible to install it. Does `pip install typing` work well?
There are requirements just in setup.py, not requirements.txt. There are no specific versions of libraries. It should work fine (https://packaging.python.org/discussions/install-requires-vs-requirements/)
