### ISSUE TITLE
ModuleNotFoundError: No module named 'fim'

### ISSUE THREAD

**Issue by vorsprungdurchtae** [lukassykora/actionrules#29]
Hi,

I am currently reproduce experiments of CausalRulesDiscovery, which is implemented based on the actionrules.
However, the error above occurs every time when I execute the files.
Is it possible to substitute another library?
It would be thankful if someone shares idea to resolve this issue.

Kind regards

<img width="1005" alt="Bildschirmfoto 2021-11-29 um 15 56 09" src="https://user-images.githubusercontent.com/16806315/143890524-b4ca2b5e-49f8-4bcc-8858-0e6ea2e551ee.png">

**Comment by kliegr** [comment]
Have you tried installing pyfim separately, using 

    pip install pyfim

**Comment by vorsprungdurchtae** [comment]
I got tried, however, it keeps showing the same error.
Is this import fim exchangeable to pyfim?

**Comment by lukassykora** [comment]
Hi, the package is called pyfim but it uses "fim" for import. You can find the pyfim package on PyPi: https://pypi.org/project/pyfim/.
